services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - api_postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  api_postgres:
